### ISSUE TITLE
Visibility-related error during initial build

### ISSUE THREAD

**Issue by melanuria** [google-research/turkish-morphology#4]
I get the following error message during the initial build operation (on Lubuntu 19.10):

"//scripts/BUILD.bazel:36:1: in cc_binary rule //scripts:print_analyses: target '//src/analyzer:build_fst' is not visible from target '//scripts:print_analyses'. Check the visibility declaration of the former target if you think the dependency is legitimate."

The problem can be solved by changing the relevant part of Line 15 in src/analyzer/BUILD.bazel from "//public:__pkg__" to "//visibility:public".

**Comment by ozturel** [comment]
Ah, sorry about that! You should be able to build the print_analyses script right now.
