### ISSUE TITLE
Please don't retag!

### ISSUE THREAD

**Issue by alerque** [google-research/turkish-morphology#9]
Please do not delete and re-add git tags! When tags get pushed publicly that starts a chain reaction where releases start getting pushed into distros. This process usually involves things like checksums to make sure the releases don't change since what was approved by the distro. You screw this all up when you re-post tags. If something goes wrong with a release cycle add a new patch release tag by bumping the number. If you urgently need to (e.g. for major security flaws or releases that would brick a system if used) you can pull a tag, but do not repost the same tag later!

(v1.2.5 just got reposted an hour or so after first release and it's already in some Arch package repos, now broken.)

**Comment by ozturel** [comment]
Very sorry! Will add a patch release tag, if something goes wrong during the upcoming releases.

**Comment by alerque** [comment]
Teşekkürler kolay gelsin.
